<?php
$car_id=$_POST['car_id'];
$customer_id=$_POST['customer_id'];
$service_id=$_POST['service_id'];
$jobcard_date=$_POST['jobcard_date'];
$jobcard_time=$_POST['jobcard_time'];
$year_of_mfd=$_POST['year_of_mfd'];
$fuel_type=$_POST['fuel_type'];
$engine_no=$_POST['engine_no'];
$chassis_no=$_POST['chassis_no'];
$total_kms=$_POST['total_kms'];
$date_estimate=$_POST['date_estimate'];
$time_estimate=$_POST['time_estimate'];
$price_estimate=$_POST['price_estimate'];
$employee_id=$_POST['employee_id'];
include('db.php');
$sql="insert into jobcard_details values(null,'$car_id','$customer_id','$service_id','$jobcard_date','$jobcard_time','$year_of_mfd','$fuel_type','$engine_no','$chassis_no','$total_kms','$date_estimate','$time_estimate','$price_estimate','$employee_id')";
mysql_query($sql);
?>
<script>
alert('inserted..');
document.location="jobcard_details_form.php";
</script>